/*
 * Centralized application feature toggles and profiles.
 *
 * Each macro defaults to enabled but can be overridden at compile time
 * by defining the symbol before including this header (for example via
 * compiler command line options).
 *
 * Copyright (c) 2024, @momentics <momentics@gmail.com>
 * All rights reserved.
 *
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * The software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#pragma once

int app_main(void);

#define APP_FEATURE_PROFILE_MINIMAL 0
#define APP_FEATURE_PROFILE_MEDIUM  1

#ifndef APP_FEATURE_PROFILE
#define APP_FEATURE_PROFILE APP_FEATURE_PROFILE_MEDIUM
#endif

#if (APP_FEATURE_PROFILE != APP_FEATURE_PROFILE_MINIMAL) && \
    (APP_FEATURE_PROFILE != APP_FEATURE_PROFILE_MEDIUM)
#error "Unknown APP_FEATURE_PROFILE"
#endif

#if APP_FEATURE_PROFILE == APP_FEATURE_PROFILE_MINIMAL
#define APP_FEATURE_DEFAULT_ENABLED_DUMP_COMMAND      1
#define APP_FEATURE_DEFAULT_ENABLE_SCANBIN_COMMAND    1
#define APP_FEATURE_DEFAULT_ENABLE_USART_COMMAND      1
#define APP_FEATURE_DEFAULT_ENABLE_CONFIG_COMMAND     1
#define APP_FEATURE_DEFAULT_ENABLE_VBAT_OFFSET        0
#define APP_FEATURE_DEFAULT_ENABLE_INFO               1
#define APP_FEATURE_DEFAULT_ENABLE_COLOR              1
#define APP_FEATURE_DEFAULT_ENABLE_TRANSFORM          0
#define APP_FEATURE_DEFAULT_ENABLE_SAMPLE             0
#define APP_FEATURE_DEFAULT_ENABLE_I2C                1
#define APP_FEATURE_DEFAULT_ENABLE_LCD                1
#define APP_FEATURE_DEFAULT_ENABLE_HARDFAULT_DEBUG    0
#define APP_FEATURE_DEFAULT_ENABLE_TEST               0
#define APP_FEATURE_DEFAULT_ENABLE_STAT               1
#define APP_FEATURE_DEFAULT_ENABLE_GAIN               1
#define APP_FEATURE_DEFAULT_ENABLE_PORT               0
#define APP_FEATURE_DEFAULT_ENABLE_SI5351_REG_WRITE   1
#define APP_FEATURE_DEFAULT_ENABLE_I2C_TIMINGS        1
#define APP_FEATURE_DEFAULT_ENABLE_BAND               0
#define APP_FEATURE_DEFAULT_ENABLE_THREADS            1
#define APP_FEATURE_DEFAULT_ENABLE_SI5351_TIMINGS     1
#else
#define APP_FEATURE_DEFAULT_ENABLED_DUMP_COMMAND      1
#define APP_FEATURE_DEFAULT_ENABLE_SCANBIN_COMMAND    1
#define APP_FEATURE_DEFAULT_ENABLE_USART_COMMAND      1
#define APP_FEATURE_DEFAULT_ENABLE_CONFIG_COMMAND     1
#define APP_FEATURE_DEFAULT_ENABLE_VBAT_OFFSET        1
#define APP_FEATURE_DEFAULT_ENABLE_INFO               1
#define APP_FEATURE_DEFAULT_ENABLE_COLOR              1
#define APP_FEATURE_DEFAULT_ENABLE_TRANSFORM          1
#define APP_FEATURE_DEFAULT_ENABLE_SAMPLE             1
#define APP_FEATURE_DEFAULT_ENABLE_I2C                1
#define APP_FEATURE_DEFAULT_ENABLE_LCD                1
#define APP_FEATURE_DEFAULT_ENABLE_HARDFAULT_DEBUG    0
#define APP_FEATURE_DEFAULT_ENABLE_TEST               1
#define APP_FEATURE_DEFAULT_ENABLE_STAT               1
#define APP_FEATURE_DEFAULT_ENABLE_GAIN               1
#define APP_FEATURE_DEFAULT_ENABLE_PORT               1
#define APP_FEATURE_DEFAULT_ENABLE_SI5351_REG_WRITE   1
#define APP_FEATURE_DEFAULT_ENABLE_I2C_TIMINGS        1
#define APP_FEATURE_DEFAULT_ENABLE_BAND               1
#define APP_FEATURE_DEFAULT_ENABLE_THREADS            1
#define APP_FEATURE_DEFAULT_ENABLE_SI5351_TIMINGS     1
#endif

#ifndef ENABLED_DUMP_COMMAND
#define ENABLED_DUMP_COMMAND APP_FEATURE_DEFAULT_ENABLED_DUMP_COMMAND
#endif

#ifndef ENABLE_SCANBIN_COMMAND
#define ENABLE_SCANBIN_COMMAND APP_FEATURE_DEFAULT_ENABLE_SCANBIN_COMMAND
#endif

#ifndef ENABLE_USART_COMMAND
#define ENABLE_USART_COMMAND APP_FEATURE_DEFAULT_ENABLE_USART_COMMAND
#endif

#ifndef ENABLE_CONFIG_COMMAND
#define ENABLE_CONFIG_COMMAND APP_FEATURE_DEFAULT_ENABLE_CONFIG_COMMAND
#endif

#ifndef ENABLE_VBAT_OFFSET_COMMAND
#define ENABLE_VBAT_OFFSET_COMMAND APP_FEATURE_DEFAULT_ENABLE_VBAT_OFFSET
#endif

#ifndef ENABLE_INFO_COMMAND
#define ENABLE_INFO_COMMAND APP_FEATURE_DEFAULT_ENABLE_INFO
#endif

#ifndef ENABLE_COLOR_COMMAND
#define ENABLE_COLOR_COMMAND APP_FEATURE_DEFAULT_ENABLE_COLOR
#endif

#ifndef ENABLE_TRANSFORM_COMMAND
#define ENABLE_TRANSFORM_COMMAND APP_FEATURE_DEFAULT_ENABLE_TRANSFORM
#endif

#ifndef ENABLE_SAMPLE_COMMAND
#define ENABLE_SAMPLE_COMMAND APP_FEATURE_DEFAULT_ENABLE_SAMPLE
#endif

#ifndef ENABLE_I2C_COMMAND
#define ENABLE_I2C_COMMAND APP_FEATURE_DEFAULT_ENABLE_I2C
#endif

#ifndef ENABLE_LCD_COMMAND
#define ENABLE_LCD_COMMAND APP_FEATURE_DEFAULT_ENABLE_LCD
#endif

#ifndef ENABLE_HARD_FAULT_HANDLER_DEBUG
#define ENABLE_HARD_FAULT_HANDLER_DEBUG APP_FEATURE_DEFAULT_ENABLE_HARDFAULT_DEBUG
#endif

#ifndef ENABLE_TEST_COMMAND
#define ENABLE_TEST_COMMAND APP_FEATURE_DEFAULT_ENABLE_TEST
#endif

#ifndef ENABLE_STAT_COMMAND
#define ENABLE_STAT_COMMAND APP_FEATURE_DEFAULT_ENABLE_STAT
#endif

#ifndef ENABLE_GAIN_COMMAND
#define ENABLE_GAIN_COMMAND APP_FEATURE_DEFAULT_ENABLE_GAIN
#endif

#ifndef ENABLE_PORT_COMMAND
#define ENABLE_PORT_COMMAND APP_FEATURE_DEFAULT_ENABLE_PORT
#endif

#ifndef ENABLE_SI5351_REG_WRITE
#define ENABLE_SI5351_REG_WRITE APP_FEATURE_DEFAULT_ENABLE_SI5351_REG_WRITE
#endif

#ifndef ENABLE_I2C_TIMINGS
#define ENABLE_I2C_TIMINGS APP_FEATURE_DEFAULT_ENABLE_I2C_TIMINGS
#endif

#ifndef ENABLE_BAND_COMMAND
#define ENABLE_BAND_COMMAND APP_FEATURE_DEFAULT_ENABLE_BAND
#endif

#ifndef ENABLE_THREADS_COMMAND
#define ENABLE_THREADS_COMMAND APP_FEATURE_DEFAULT_ENABLE_THREADS
#endif

#ifndef ENABLE_SI5351_TIMINGS
#define ENABLE_SI5351_TIMINGS APP_FEATURE_DEFAULT_ENABLE_SI5351_TIMINGS
#endif
